spring:
#Datasource configuration
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thymeleaf?useSSL=false
    username: thymeleaf
    password: thymeleaf
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
#Liquibase configuration
liquibase:
  change-log: classpath:/liquibase/db.changelog-master.xml
  drop-first: false
  enabled: true
  url: jdbc:mysql://localhost:3306/thymeleaf?useSSL=false
  user: thymeleaf
  password: thymeleaf
  contexts: mysql
